return {
  ui = {
    package_pending = " ",
    package_installed = " ",
    package_uninstalled = " ﮊ",
    modified = "✥",
    indicator = "▎",
    buffer_close = "",
    left_trunc = "",
    right_trunc = "",
    left_separator = "",
    right_separator = "",
  },
  kind = {
    Class = "ﴯ",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Number = "",
    Operator = "",
    Package = "",
    Property = "ﰠ",
    Reference = "",
    Snippet = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
    -- ccls-specific icons.
    TypeAlias = "",
    Parameter = "",
    StaticMethod = "",
    Macro = "",
  },
  type = {
    Array = "",
    Boolean = "",
    Null = "ﳠ",
    Number = "",
    Object = "",
    String = "",
  },
  cmp = {
    Copilot = "",
    Copilot_alt = "",
    nvim_lsp = "",
    nvim_lua = "",
    path = "",
    buffer = "",
    spell = "暈",
    luasnip = "",
    treesitter = "",
  },
  diagnostics = {
    warning = " ",
    error = " ",
    information = "",
  },
}
